networks:
  snowbin:

volumes:
  postgres-data:

services:
  postgres:
    networks:
      - snowbin
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    env_file: .env
    restart: always
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    logging:
      options:
        max-size: "20m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
